services: 
  api: 
    image: malkh/python_crud_api
    depends_on:
      - postgres
    ports: 
      - 80:8000
    # bind mount syncs the local directories with the usr/src/app directory in the container

    # command: uvicorn src.main:app --host 0.0.0.0 --port 8000

    environment: 
    - DATABASE_HOSTNAME=${DATABASE_HOSTNAME} # this references the postgres below
    - DATABASE_PORT=${DATABASE_PORT}
    - DATABASE_PASSWORD=${DATABASE_PASSWORD}  
    - DATABASE_NAME=${DATABASE_NAME}
    - DATABASE_USERNAME=${DATABASE_USERNAME}
    - SECRET_KEY=${SECRET_KEY}
    - ALGORITHM=${ALGORITHM}
    - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}

  postgres:
    image: postgres
    # restart: always
    environment: 
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}  
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: